/*****************************************************************************/
/* D2K: A Doom Source Port for the 21st Century                              */
/*                                                                           */
/* Copyright (C) 2014: See COPYRIGHT file                                    */
/*                                                                           */
/* This file is part of D2K.                                                 */
/*                                                                           */
/* D2K is free software: you can redistribute it and/or modify it under the  */
/* terms of the GNU General Public License as published by the Free Software */
/* Foundation, either version 2 of the License, or (at your option) any      */
/* later version.                                                            */
/*                                                                           */
/* D2K is distributed in the hope that it will be useful, but WITHOUT ANY    */
/* WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS */
/* FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more    */
/* details.                                                                  */
/*                                                                           */
/* You should have received a copy of the GNU General Public License along   */
/* with D2K.  If not, see <http://www.gnu.org/licenses/>.                    */
/*                                                                           */
/*****************************************************************************/

#ifndef D2K_SPRITE_H__
#define D2K_SPRITE_H__

typedef enum {
  D2K_SPRITE_NUM_TROO,
  D2K_SPRITE_NUM_SHTG,
  D2K_SPRITE_NUM_PUNG,
  D2K_SPRITE_NUM_PISG,
  D2K_SPRITE_NUM_PISF,
  D2K_SPRITE_NUM_SHTF,
  D2K_SPRITE_NUM_SHT2,
  D2K_SPRITE_NUM_CHGG,
  D2K_SPRITE_NUM_CHGF,
  D2K_SPRITE_NUM_MISG,
  D2K_SPRITE_NUM_MISF,
  D2K_SPRITE_NUM_SAWG,
  D2K_SPRITE_NUM_PLSG,
  D2K_SPRITE_NUM_PLSF,
  D2K_SPRITE_NUM_BFGG,
  D2K_SPRITE_NUM_BFGF,
  D2K_SPRITE_NUM_BLUD,
  D2K_SPRITE_NUM_PUFF,
  D2K_SPRITE_NUM_BAL1,
  D2K_SPRITE_NUM_BAL2,
  D2K_SPRITE_NUM_PLSS,
  D2K_SPRITE_NUM_PLSE,
  D2K_SPRITE_NUM_MISL,
  D2K_SPRITE_NUM_BFS1,
  D2K_SPRITE_NUM_BFE1,
  D2K_SPRITE_NUM_BFE2,
  D2K_SPRITE_NUM_TFOG,
  D2K_SPRITE_NUM_IFOG,
  D2K_SPRITE_NUM_PLAY,
  D2K_SPRITE_NUM_POSS,
  D2K_SPRITE_NUM_SPOS,
  D2K_SPRITE_NUM_VILE,
  D2K_SPRITE_NUM_FIRE,
  D2K_SPRITE_NUM_FATB,
  D2K_SPRITE_NUM_FBXP,
  D2K_SPRITE_NUM_SKEL,
  D2K_SPRITE_NUM_MANF,
  D2K_SPRITE_NUM_FATT,
  D2K_SPRITE_NUM_CPOS,
  D2K_SPRITE_NUM_SARG,
  D2K_SPRITE_NUM_HEAD,
  D2K_SPRITE_NUM_BAL7,
  D2K_SPRITE_NUM_BOSS,
  D2K_SPRITE_NUM_BOS2,
  D2K_SPRITE_NUM_SKUL,
  D2K_SPRITE_NUM_SPID,
  D2K_SPRITE_NUM_BSPI,
  D2K_SPRITE_NUM_APLS,
  D2K_SPRITE_NUM_APBX,
  D2K_SPRITE_NUM_CYBR,
  D2K_SPRITE_NUM_PAIN,
  D2K_SPRITE_NUM_SSWV,
  D2K_SPRITE_NUM_KEEN,
  D2K_SPRITE_NUM_BBRN,
  D2K_SPRITE_NUM_BOSF,
  D2K_SPRITE_NUM_ARM1,
  D2K_SPRITE_NUM_ARM2,
  D2K_SPRITE_NUM_BAR1,
  D2K_SPRITE_NUM_BEXP,
  D2K_SPRITE_NUM_FCAN,
  D2K_SPRITE_NUM_BON1,
  D2K_SPRITE_NUM_BON2,
  D2K_SPRITE_NUM_BKEY,
  D2K_SPRITE_NUM_RKEY,
  D2K_SPRITE_NUM_YKEY,
  D2K_SPRITE_NUM_BSKU,
  D2K_SPRITE_NUM_RSKU,
  D2K_SPRITE_NUM_YSKU,
  D2K_SPRITE_NUM_STIM,
  D2K_SPRITE_NUM_MEDI,
  D2K_SPRITE_NUM_SOUL,
  D2K_SPRITE_NUM_PINV,
  D2K_SPRITE_NUM_PSTR,
  D2K_SPRITE_NUM_PINS,
  D2K_SPRITE_NUM_MEGA,
  D2K_SPRITE_NUM_SUIT,
  D2K_SPRITE_NUM_PMAP,
  D2K_SPRITE_NUM_PVIS,
  D2K_SPRITE_NUM_CLIP,
  D2K_SPRITE_NUM_AMMO,
  D2K_SPRITE_NUM_ROCK,
  D2K_SPRITE_NUM_BROK,
  D2K_SPRITE_NUM_CELL,
  D2K_SPRITE_NUM_CELP,
  D2K_SPRITE_NUM_SHEL,
  D2K_SPRITE_NUM_SBOX,
  D2K_SPRITE_NUM_BPAK,
  D2K_SPRITE_NUM_BFUG,
  D2K_SPRITE_NUM_MGUN,
  D2K_SPRITE_NUM_CSAW,
  D2K_SPRITE_NUM_LAUN,
  D2K_SPRITE_NUM_PLAS,
  D2K_SPRITE_NUM_SHOT,
  D2K_SPRITE_NUM_SGN2,
  D2K_SPRITE_NUM_COLU,
  D2K_SPRITE_NUM_SMT2,
  D2K_SPRITE_NUM_GOR1,
  D2K_SPRITE_NUM_POL2,
  D2K_SPRITE_NUM_POL5,
  D2K_SPRITE_NUM_POL4,
  D2K_SPRITE_NUM_POL3,
  D2K_SPRITE_NUM_POL1,
  D2K_SPRITE_NUM_POL6,
  D2K_SPRITE_NUM_GOR2,
  D2K_SPRITE_NUM_GOR3,
  D2K_SPRITE_NUM_GOR4,
  D2K_SPRITE_NUM_GOR5,
  D2K_SPRITE_NUM_SMIT,
  D2K_SPRITE_NUM_COL1,
  D2K_SPRITE_NUM_COL2,
  D2K_SPRITE_NUM_COL3,
  D2K_SPRITE_NUM_COL4,
  D2K_SPRITE_NUM_CAND,
  D2K_SPRITE_NUM_CBRA,
  D2K_SPRITE_NUM_COL6,
  D2K_SPRITE_NUM_TRE1,
  D2K_SPRITE_NUM_TRE2,
  D2K_SPRITE_NUM_ELEC,
  D2K_SPRITE_NUM_CEYE,
  D2K_SPRITE_NUM_FSKU,
  D2K_SPRITE_NUM_COL5,
  D2K_SPRITE_NUM_TBLU,
  D2K_SPRITE_NUM_TGRN,
  D2K_SPRITE_NUM_TRED,
  D2K_SPRITE_NUM_SMBT,
  D2K_SPRITE_NUM_SMGT,
  D2K_SPRITE_NUM_SMRT,
  D2K_SPRITE_NUM_HDB1,
  D2K_SPRITE_NUM_HDB2,
  D2K_SPRITE_NUM_HDB3,
  D2K_SPRITE_NUM_HDB4,
  D2K_SPRITE_NUM_HDB5,
  D2K_SPRITE_NUM_HDB6,
  D2K_SPRITE_NUM_POB1,
  D2K_SPRITE_NUM_POB2,
  D2K_SPRITE_NUM_BRS1,
  D2K_SPRITE_NUM_TLMP,
  D2K_SPRITE_NUM_TLP2,
  D2K_SPRITE_NUM_TNT1,
  D2K_SPRITE_NUM_DOGS,
  D2K_SPRITE_NUM_PLS1,
  D2K_SPRITE_NUM_PLS2,
  D2K_SPRITE_NUM_BON3,
  D2K_SPRITE_NUM_BON4,
  D2K_SPRITE_NUM_MAX,
} D2KSpriteNum;

#endif

/* vi: set et ts=2 sw=2: */
